[project]
name = "cinescrapper"
version = "0.1.0"
description = "A Python project to scrape movie data"
authors = [
    { name="Yukeshkumar N", email="yukesh@live.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "beautifulsoup4",
    "pymongo"
]

[project.optional-dependencies]
dev = [
    "pytest",             # For testing
    "pytest-cov",         # Optional: for coverage reports
]

[project.scripts]
cinescrapper = "cinescrapper.__main__:main"

[tool.setuptools]
packages = ["cinescrapper"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"
markers = [
    "integration: marks tests that perform live API calls (deselect with '-m \"not integration\"')",
]
